### ISSUE TITLE
Vamos a mejorarlo!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-AlbaGomezPerez#1]
Buen trabajo @AlbaGomezPerez  !

Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Termina de añadir los componentes finales: recuerda que **PokeList** suele contener la lista de elementos y **Pokemon** tendrá solo la tarjeta
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by AlbaGomezPerez** [comment]
- [ ] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con npm start. Si algo falla, hay que arreglarlo antes de continuar.

- [ ] Termina de añadir los componentes finales: recuerda que PokeList suele contener la lista de elementos y Pokemon tendrá solo la tarjeta 67fdf5c3e94b99d6f55aee8004385ea7896017b2

- [ ] Usa el id de cada pokemon para el key de react cuando mapeas y creas un listado de componentes a0485f8a569f8ac61360ee1b5d5c74b630d3afd5
 
- [ ] Añade estilos (un archivo sass o css por componente) d2c23ddf473876644f5184e0aac3032b4bf24399

- [ ] Usa propTypes para comprobar el tipo de dato de las props 408e3544ab03c2651dac8a111dd62556119bf0ab

- [ ] Revisa los metadatos en index.html (lang, title...) 281880ab1e5b9f9bbd98513ea5a36c4784511560

- [ ] Limpia e indenta el código 98cec138b53bb60da084ba0541d0c021b7114092

- [ ] Elimina archivos sin usar y sus referencias fab2b3685cbc803740f68bf3590d2d6abd6bdeb9

- [ ] Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App. Pasar este dato al componente Pokemon por props. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito 633225c0ba2894f98194119f9e2a2bce34353383

**Comment by oneeyedman** [comment]
Lo damos por válido pero los tipos vienen en un array y hay que pintarlo con map()
